name: Dependabot auto-approve
on: pull_request


jobs:
  dependabot:
    name: 'Dependabot'
    uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
    with:
      github-token: '${{ secrets.GITHUB_TOKEN }}'
